---
project_name: kube-volume-autoresizer
builds:
  - main: ./main.go
    binary: kube-volume-autoresizer
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
archives:
  - format: binary
    files:
      - none*
    replacements:
      386: i386
      amd64: x86_64
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "tarekesmail/kube-volume-autoresizer:latest"
      - "tarekesmail/kube-volume-autoresizer:{{ .Tag }}"
      - "tarekesmail/kube-volume-autoresizer:v{{ .Major }}"
    binaries:
      - kube-volume-cleaner
release:
  github:
    owner: tarekesmail
    name: kube-volume-autoresizer
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
